src/blade/proto_library_target.py
src/blade/rules_generator.py

Use protobuf compiler --descriptor_set_out --include_imports to generate a FileDescriptorSet file

Generate protobuf descriptor set in blade

---

src/blade/java_targets.py

The format of exclusions is the same as deps: dir/path:target
Currently maven id(group:artifact:version) is not supported in exclusions. If you want to exclude a maven jar, you need to add the corresponding target within another BUILD file, for instance:
thirdparty/blade/BUILD
maven_jar (
name = 'protobuf',
id = 'com.google.protobuf:protobuf-java:2.6.1',
)
foo/bar/BUILD
java_binary(
name = 'foo_bar',
main_class = 'AAA',
deps = [
':foo',
'//project/proto:log',
],
exclusions = [
'//thirdparty/blade:protobuf',
'//project/proto:log',
]
)
Each target in the list of exclusions is supposed to be excluded accordingly:
1. java_binary: target jar is excluded in the lib folder of one.jar
2. java_fat_library: all the contents(directory structure, class files) of the target jar are excluded in the fat …

Support exclusions in java_binary and java_fat_library

---

src/blade/proto_library_target.py
src/blade/scons_helper.py

Merge "generate protobuf descriptor set" into develop branch

---

src/blade/java_targets.py

1. Use set to store all the artifacts with same group:artifact:version
2. Add scope and modify the warnings

Fix maven test jar when detecting conflicted dependencies

---

src/blade/java_targets.py
src/blade/scala_targets.py

Do not support maven id(group:artifact:version) in deps

---

src/blade/java_targets.py
src/blade/maven.py

maven_jar (
&nbsp;&nbsp;&nbsp;&nbsp;       name = 'mrunit',
&nbsp;&nbsp;&nbsp;&nbsp;       id = 'org.apache.mrunit:mrunit:1.0.0',
&nbsp;&nbsp;&nbsp;&nbsp;      classifier = 'hadoop2',
)

Support classifier in maven_jar

---

src/blade/java_targets.py
src/blade/proto_library_target.py
src/blade/scala_targets.py

1. Add exported_deps/provided_deps in scala_library
2. Add exclusions in scala_fat_library

Add dependency options for scala targets

---

src/blade/java_targets.py
src/blade/maven.py

Write maven log to build output directory

---

src/blade/proto_library_target.py

Proto_library can only depend on proto_library/gen_rule

---

src/blade/blade.py
src/blade/command_args.py
src/blade/dependency_analyzer.py

- Do not generate SConstruct in blade query
- Make use of results of topological sorting for depended query

Optimize blade query

---

src/blade/java_targets.py
src/blade/scons_helper.py

JavaSource

---

src/blade/py_targets.py
src/blade/scons_helper.py

1. Remove prebuilt in py_library  
2. Add base parameter in py_library/py_binary/py_test
3. Revise a few message/indent/comment

Python targets

---

src/blade/command_args.py
src/blade/configparse.py
src/blade/dependency_analyzer.py
src/blade/proto_library_target.py
src/blade/rules_generator.py
src/blade/scons_helper.py

Generate go source to the build directory currently like C++/Java.

Protobuf generates go source

---

src/blade/blade.py
src/blade/command_args.py

Dependency tree query

---

src/blade/go_targets.py
src/blade/load_build_files.py
src/blade/proto_library_target.py
src/blade/rules_generator.py
src/blade/scons_helper.py

Go targets

---

src/blade/java_targets.py

Generate scons var for prebuilt jar

---

src/blade/console.py
src/blade/scons_helper.py

1. Always set $SPAWN
2. Log every command executed by scons to blade_scons.log
3. Set colored output if not verbose
4. Change log file to use line buffering for better debugging

scons log change

---

install
vim/README.md
vim/ftdetect/blade.vim
vim/ftdetect/blade_root.vim
vim/indent/blade_root.vim
vim/syntax/blade.vim
vim/syntax/blade_root.vim

add more vim syntax plugins
remove the code that modify $HOME/.vimrc

add vim plugins

---

src/blade/thrift_helper.py
src/blade/thrift_library.py

1. Support path/to/foo.thrift in srcs of thrift_library
2. Revise a few implementation of thrift_library

Support path/to/foo.thrift in srcs of thrift_library

---

src/blade/py_targets.py
src/blade/scons_helper.py

1. Rename python target classes
2. Add visibility in py_library
3. Fix path error when generating pyc during py_compile

Revise python targets

---

src/blade/blade_main.py
src/blade/build_attributes.py
src/blade/cc_targets.py
src/blade/configparse.py
src/blade/load_build_files.py

1. 提取 TargetAttributes 到独立 module(build_attributes)
2. configparse/load_build_files import build_attributes
3. 修正了一些注释

Global build attributes

---

src/blade/blade_main.py
src/blade/scons_helper.py

1. 每次清空 classes 目录，打包时递归打包 classes 目录
2. 根据 sources 判断编译生成的 classes 是否完整，即：
每个 Foo.java 至少生成 Foo.class

Check if java classes are complete in classes directory

---

src/blade/blade.py
src/blade/cc_targets.py
src/blade/target.py

- Use depended_target dict for _prebuilt_cc_library_is_depended query
- Refine env_name in Target

A few minor optimizations

---

src/blade/cc_targets.py
src/blade/gen_rule_target.py
src/blade/rules_generator.py
src/blade/toolchain.py

1. Ninja build for secure cc_library
2. Modify a few variable/output color

Ninja build system part 3

---

src/blade/cc_targets.py
src/blade/java_targets.py
src/blade/proto_library_target.py
src/blade/rules_generator.py
src/blade/sh_test_target.py
src/blade/thrift_library.py
src/blade/toolchain.py

1 Ninja build for sh_test/thrift_library
2 Refine arguments and dependencies in resource_library/proto_library

Ninja build system part 4

---

src/blade/cc_targets.py
src/blade/console.py
src/blade/gen_rule_target.py
src/blade/lex_yacc_target.py
src/blade/proto_library_target.py
src/blade/py_targets.py
src/blade/rules_generator.py
src/blade/toolchain.py

1. Ninja build for lex_yacc_library
2. Ninja build for py_library/py_binary/proto_library of python

Ninja build system part 5

---

src/blade/blade_main.py
src/blade/cc_targets.py
src/blade/command_args.py
src/blade/cu_targets.py
src/blade/dependency_analyzer.py

1. optimize expand_deps generation
2. optimize expors_incs
3. optimize topological_sort and make it py3k compatiable
4. optimize cpplint: don't call _get_opened_files if cpplint is disabled

Performance optimizations:

---

src/blade/package_target.py
src/blade/rules_generator.py
src/blade/toolchain.py

Ninja build system part 7

---

src/blade/blade.py
src/blade/blade_main.py
src/blade/blade_util.py
src/blade/load_build_files.py

normalize all targets before load
move find_blade_root_dir into blade_util

command line target syntax support absolute path

---

src/blade/binary_runner.py
src/blade/blade.py
src/blade/blade_main.py
src/blade/blade_platform.py
src/blade/cc_targets.py
src/blade/command_args.py
src/blade/configparse.py
src/blade/java_targets.py
src/blade/rules_generator.py

make debug-info-level configurable
make java_home optional

debug-info-level configurable and java-home fix

---

src/blade/binary_runner.py
src/blade/blade_main.py
src/blade/configparse.py
src/blade/proto_library_target.py
src/blade/py_targets.py
src/blade/scons_helper.py
src/blade/toolchain.py

add prebuilt py_library
prebuilt py_library embedded into py_binary

prebuilt py_library

---

src/blade/scons_helper.py

同样遇到了这个问题 https://github.com/chen3feng/typhoon-blade/issues/303
修复提交。

增加转义修复双引号导致的version.cpp不工作问题

---

blade.conf
doc/blade_command_line_zn_CN.md
doc/build_cache_zh_CN.md
example/BLADE_ROOT.EXAMPLE
google-libs.conf
opensource.conf
src/blade/build_environment.py
src/blade/command_args.py
src/blade/config.py
src/blade/rules_generator.py
src/test/testdata/BLADE_ROOT.TEST
typhoon.conf
vim/syntax/blade_root.vim

ccache is much better than the scons cache, and we plan to phase out using scons in the future,
dccc is an aborted project.

Cleanup code, remove-scons-cache-and-dccc

---

src/blade/blade_main.py
src/blade/test_runner.py

Bugfix quiet mode exit code

---

blade
src/blade/blade_main.py
src/blade/build_environment.py
src/blade/console.py
src/blade/rules_generator.py
src/blade/scons_helper.py
src/blade/test_runner.py
src/blade/toolchain.py

Fix color issues

---

doc/zh_CN/test.md
src/blade/blade_main.py
src/blade/build_manager.py
src/blade/command_args.py
src/blade/target.py
src/blade/test_runner.py

Support skip specified tests explicitly by --skip-tests

Support --skip-tests

---

src/blade/rules_generator.py

Fix thrift_gen_params bug

---

src/blade/blade_main.py
src/blade/build_manager.py
src/blade/command_args.py
src/blade/config.py
src/blade/target.py

Support dump config and targets

---

src/blade/go_targets.py
src/blade/rules_generator.py

Reverts chen3feng/blade-build#552

Revert "blade add extra_goflags"

---

src/blade/go_targets.py
src/blade/rules_generator.py

add extra_goflags

---

src/blade/blade_platform.py
src/blade/cc_targets.py
src/blade/rules_generator.py

1. Use name from CC to determine whether it's gcc or clang
2. Different commands to obtain target architecture
3. Refactor code related to platform information into script header generator

Support llvm/clang part 1

---

src/blade/config.py
src/blade/go_targets.py
src/blade/proto_library_target.py
src/blade/rules_generator.py

golang code doesn't exist in the root of repository

feat(gomod): support gomod in onetree repository

---

src/blade/proto_library_target.py

1. Refactor a few code related to protoc plugin dependencies
2. Add protoc plugin as an implicit dependency of the generated sources

protoc plugin dependencies refactor

---

src/blade/lex_yacc_target.py
src/blade/target.py

Add `.h` as implicit output to yacc rule

Fix lex/yacc dep issue

---

src/blade/cc_targets.py
src/blade/gen_rule_target.py
src/blade/go_targets.py
src/blade/java_targets.py
src/blade/lex_yacc_target.py
src/blade/package_target.py
src/blade/proto_library_target.py
src/blade/py_targets.py
src/blade/resource_library_target.py
src/blade/scala_targets.py
src/blade/sh_test_target.py
src/blade/target.py
src/blade/thrift_library.py

Adjust the parameter order of Target.ninja_build

---

src/blade/blade_util.py
src/blade/gen_rule_target.py
src/blade/java_targets.py
src/blade/package_target.py
src/blade/sh_test_target.py
src/blade/target.py
src/blade/toolchain.py

Refactoring: Move location_re to target.py and rename to upper case
Fix issue: env USER doesn't exist in docker

Small fixes

---

blade.conf
src/blade/__init__.py
src/blade/binary_runner.py
src/blade/blade_main.py
src/blade/build_manager.py
src/blade/cc_targets.py
src/blade/gen_rule_target.py
src/blade/java_targets.py
src/blade/load_build_files.py
src/blade/maven.py
src/blade/proto_library_target.py
src/blade/rules_generator.py
src/blade/swig_library_target.py
src/blade/target.py
src/blade/test_runner.py
src/blade/thrift_library.py

Build dir optimize

---

src/blade/cc_targets.py
src/blade/console.py
src/blade/cu_targets.py
src/blade/fbthrift_library.py
src/blade/gen_rule_target.py
src/blade/go_targets.py
src/blade/java_targets.py
src/blade/lex_yacc_target.py
src/blade/package_target.py
src/blade/proto_library_target.py
src/blade/py_targets.py
src/blade/resource_library_target.py
src/blade/rules_generator.py
src/blade/scala_targets.py
src/blade/sh_test_target.py
src/blade/swig_library_target.py
src/blade/target.py
src/blade/test_runner.py
src/blade/test_scheduler.py
src/blade/thrift_helper.py
src/blade/thrift_library.py
src/test/html_test_runner.py
vim/ftdetect/blade_root.vim
vim/syntax/blade_config.vim

Super and named args

---

doc/en/config.md
doc/zh_CN/config.md
src/blade/build_manager.py
src/blade/cc_targets.py
src/blade/config.py
src/blade/gen_rule_target.py
src/blade/lex_yacc_target.py
src/blade/load_build_files.py
src/blade/proto_library_target.py
src/blade/resource_library_target.py
src/blade/rules_generator.py
src/blade/thrift_library.py
vim/syntax/blade_config.vim

hdr-dep-missing severity control
per-target verification control

Verify all hdrs deps

---

src/blade/backend.py
src/blade/blade_util.py
src/blade/builtin_tools.py
src/blade/cc_targets.py
src/blade/fbthrift_library.py
src/blade/maven.py
src/blade/proto_library_target.py
src/blade/resource_library_target.py
src/blade/swig_library_target.py
src/blade/target.py
src/blade/thrift_library.py
src/test/cc_library_test.py
src/test/testdata/test_test_runner/BUILD.TEST

Eliminate per-target `cppflags = -O2 -no-omit-frame-pointer`

move default optimize flags to root ninja file

---

src/blade/backend.py
src/blade/build_manager.py
src/blade/cc_targets.py
src/blade/cu_targets.py
src/blade/dependency_analyzer.py
src/blade/fbthrift_library.py
src/blade/java_targets.py
src/blade/load_build_files.py
src/blade/proto_library_target.py
src/blade/scala_targets.py
src/blade/target.py
src/blade/thrift_library.py

Include 3 commits:
1. split global dependents cache to each target
2. add -fdirectives-only to cc-hdrs rule to speedup command
3. split global depended_targets to each target

Refactor deps

---

doc/en/build_rules/gen_rule.md

fix typos in  gen_rule.md

---

blade.conf
src/blade/__init__.py
src/blade/blade_main.py
src/blade/blade_util.py
src/blade/config.py
src/blade/maven.py
src/test/swig_library_test.py
src/test/testdata/BLADE_ROOT.TEST
vim/syntax/blade_config.vim

remove cpplint support

---

src/blade/maven.py
vim/syntax/blade.vim

Doesn't considered classifiers when downloading classpath

Fix maven jar bugs

---

doc/en/build_rules/java.md
doc/en/config.md
doc/zh_CN/build_rules/java.md
doc/zh_CN/config.md
src/blade/config.py
src/blade/java_targets.py
tool/README.md
tool/collect-disallowed-maven-jars.py
vim/syntax/blade_config.vim

Restrict maven_jar allowed dirs

---

src/blade/backend.py

fix dump --compdb command format

---

src/blade/backend.py
src/blade/build_manager.py
src/blade/load_build_files.py

Fix #780 `.bladeskip` file is ignored when targets under it are specified in
command line or in deps of other targets

fix bug of `.bladeskip`

---

.travis.yml
src/blade/java_targets.py
src/blade/proto_library_target.py

Fix proto files dependency missing when compiling proto files

---

src/blade/load_build_files.py

optimize loading

---

src/blade/blade_util.py
src/blade/config.py
src/blade/console.py
src/blade/load_build_files.py
src/blade/target.py

add consle.diagnose

---

src/blade/cc_targets.py
src/blade/config.py
src/blade/gen_rule_target.py
src/blade/inclusion_dependency.py
src/blade/target.py

Split inclusion_dependency.py and check type for singular type

---

src/blade/cc_targets.py

prebuilt cc_library inclusion check

---

src/blade/backend.py
src/blade/cc_targets.py
src/blade/toolchain.py

Fix mac compatible issue

---

src/blade/cc_targets.py
src/blade/go_targets.py
src/blade/test_scheduler.py
src/blade/toolchain.py
src/blade/util.py
src/blade/workspace.py

Ensure stdout and stderr of command result always be string type rather than bytes.

Fix py3 popen encoding issue

---

doc/en/command_line.md
doc/zh_CN/command_line.md

Add doc for `...` under ohmyzsh

---

src/blade/build_manager.py

Fix bug: can't declare a dependency to a lib in the root directory

---

src/blade/builtin_tools.py
src/blade/util.py

Allow zip64 when create zip files (such as jar)

---

src/blade/cu_targets.py

Fix: CuTarget support .cu source file

---

doc/en/build_rules/cc.md
doc/zh_CN/build_rules/cc.md
example/BLADE_ROOT
example/common/BUILD
example/cuda/BUILD
example/cuda/cu_test.cu
example/cuda/template_cpu.cpp
example/foo/BUILD
example/thirdparty/gtest/BUILD
src/blade/backend.py
src/blade/cu_targets.py
vim/syntax/blade.vim

implement cuda_library and cuda_binary after ninja refactor #632

implement cuda_library and cuda_binary

---

blade
src/blade/load_build_files.py
src/blade/maven.py
src/blade/target_pattern.py
src/blade/toolchain.py

- fix #976: Error: Target not exist, load_build_files.py may have bug
- fix #980: 获取arch错误
- some prerequisites detection errors

Fix some bugs

---

.github/workflows/python-package.yml
src/blade/backend.py

some cuda and gcc error messages are after `Multiple...`.
e.g.
gcc:
cc1plus: all warnings being treated as errors
cuda:
error: identifier "xx" is undefined

print error message after "Multiple..."

---

src/blade/inclusion_check.py

For distributed compiling or with unexpected include related environment variables, gcc -H outputs may be invalid. Blade will output more information for assert error to help people find what's going on.

add log for level assertion in inclusion_check

---

src/blade/proto_library_target.py

When generating java files from protobuf, blade automatically adds target directory as output directory as below:
```bash
thirdparty/protobuf/bin/x86_64/protoc-2.5.0 --proto_path=. -I=thirdparty --java_out=build64_release/`dirname java/com/gdt/log_process/wx_log_convertor/conf.proto` java/com/gdt/log_process/wx_log_convertor/conf.proto
```
However, when we're going to insert some custom code by use of insertion points mechanism, it reports error whatever path we give to plugin output path:
```
[2/6] thirdparty/protobuf/bin/x86_64/protoc-2.5.0 --proto_path=. -I=thirdparty --java_out=build64_release/`dirname java/com/gdt/log_process/wx_log_convertor/conf.proto` --plugin=protoc-gen-java_field_tracking=thirdparty/protobuf/bin/plugin/governance/java_field_tracking_generator …
```

Change protobuf java plugin output directory
