src/blade/java_targets.py
src/blade/scons_helper.py

Add BladeJavaJar builder using glob and timestamp to collect generate *.class  files based on the results of Java builder.
Jar builder of scons have bugs to detect generated inner class files. See:
http://scons.tigris.org/issues/show_bug.cgi?id=1594
http://scons.tigris.org/issues/show_bug.cgi?id=2742

Add BladeJavaJar builder for Java

---

src/blade/java_targets.py
src/blade/proto_library_target.py
src/blade/target.py

Change provided_deps implementation to be consistent with maven:
Assume A,B,C,D,E is java_library and X is java_binary, X --> A means A is a dependency of X
1. X --> A --> B --> C/D and B is a provided dependency of A, then X.jar will ONLY contain A
2. X --> A --> B --> C/D and B is a provided dependency of A,
X --> E --> C
then X.jar will contain A，E，C

Blade provided_deps

---

src/blade/configparse.py
src/blade/scala_targets.py
src/blade/scons_helper.py

Scala compiler man page:
> -encoding \<encoding>
Specify character encoding used by source files.
The default value is platform-specific (Linux: "UTF8", Windows: "Cp1252"). Executing the following        code in the Scala interpreter will return the default value on your system:
scala> new java.io.InputStreamReader(System.in).getEncoding

Add source_encoding for scala targets

---

src/blade/java_targets.py
src/blade/maven.py

1. Select the version if it's explicitly specified as a direct dependency
2. Select higher version if #1 is not satisfied

Detect maven dependency conflict

---

src/blade/java_targets.py
src/blade/scons_helper.py

1. Copy resources from dependencies when generating one jar
2. Simplify warning message for maven dependency conflict
3. Only search the current test jar for test classes

Copy resources from main jar and dependencies to onejar

---

src/blade/command_args.py
src/blade/configparse.py
src/blade/java_targets.py
src/blade/rules_generator.py
src/blade/scala_targets.py
src/blade/scons_helper.py

1. Add --coverage in build options to add jacoco agent for shell script of java_test
2. Add target_under_test in java_test to declare the testing target. Currently only support one target.

Java Coverage with JaCoCo: part 1

---

src/blade/java_targets.py

1. Only support maven id group:artifact:version
2. Support wildcard * to specify a group of artifacts
3. Use path pattern match in local repository to exclude specific jars

Exclusions in java_binary/java_fat_library

---

src/blade/java_targets.py
src/blade/proto_library_target.py

* Exported_deps is used when public API of a target has return types/arguments defined in another target. This should be recursive as follows:
>    A <------ B <------exported_dep--- C <-----exported_dep--- D
>   Before change when compiling A: classpath: B + C
>   After change when compiling A:    classpath: B + C + D
* Proto_library is very typical that it should export all the dependencies because it references a message defined in another proto target and has public APIs with return type/arguments in the generated code.

Export deps recursively

---

src/blade/scons_helper.py

For example, build requires at least 2.4 but 2.3 installed locally

Check scons version at least 2.0

---

src/blade/java_targets.py
src/blade/maven.py

1. By default maven cache downloads the specified artifact and all of its dependencies transitively
2. When #1 failed, try to download the specified artifact individually and issue the warning that transitive dependencies are not available

Transitive in maven_jar

---

src/blade/dependency_analyzer.py

In topological sorting, initialize targets which is an ending target(no other targets depend on it. Out-degree is zero in the dependency graph) with empty list.

Fix KeyError when querying depended targets

---

src/blade/java_targets.py
src/blade/scala_targets.py
src/blade/scons_helper.py

1. relative file/directory to the current source directory.
- Specify the mapping path explicitly
- Generate the mapping path if source resource path satisfies maven rules
- Generate the mapping path literally
2. absolute file/directory from the blade root directory
- Specify the mapping path explicitly
- Generate the mapping path literally
- Test all the resources formats above
- Test incremental build
- Change a source file
- Add/Remove a source file/directory
- Change mapping path

Re-implement jar resource handling

---

src/blade/java_targets.py
src/blade/proto_library_target.py
src/blade/scala_targets.py
src/blade/scons_helper.py

Scons built-in Java builder have the following issues:
1. Cannot detect implicit dependencies between source files within the same package so that java build becomes unreliable during incremental build
2. In some code repositories, java sources are organized according to package/directory. When sourcepath is set to root directory, build is successful although a few deps are missing actually. [See javac documentation for more details](https://docs.oracle.com/javase/8/docs/technotes/tools/unix/javac.html#BHCJJJAJ)
Solution:
Deprecate Java builder and combine compile and package in one step.

Java: Generate jar

---

src/blade/configparse.py
src/blade/scala_targets.py

According to scalac manual:
&nbsp;&nbsp;&nbsp;&nbsp;-target:<target>           Target platform for object files. All JVM 1.5 targets are deprecated. (jvm-1.5,jvm-1.5-fjbg,jvm-1.5-asm,jvm-1.6,jvm-1.7,msil) default:jvm-1.6

Support target platform in scala_config

---

src/blade/gen_rule_target.py

- $(location //path/to:target)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;# the first out
- $(location //path/to:target 0)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;# the first out
- $(location //path/to:target 1)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;# the second out

Support $location in gen_rule

---

src/blade/java_targets.py
src/blade/package_target.py

1. Do not record mapping paths of location references
2. Record all location references [(key, type, dst)] as a separate value

Record location references as a separate depending value

---

src/blade/configparse.py
src/blade/proto_library_target.py
src/blade/scons_helper.py

- Support only @@protoc_insertion_point of protoc, i.e. plugins **DONOT** generate their own files.
- Supported languages: cpp, java, python
1. Define a protoc plugin in BLADE_ROOT
2. Assign a protoc plugin for proto_library

Protoc plugin

---

src/blade/load_build_files.py

#239
https://github.com/chen3feng/typhoon-blade/issues/239
在大小写不敏感的文件系统上，名为小写build的文件夹会被识别为blade的BUILD文件
进而加载失败。
一个这样的build文件夹的例子是：
https://github.com/apache/thrift/tree/0.9.3/build
本改动解决了这个问题。
Signed-off-by: Huahang Liu huahang.liu@gmail.com

解决build文件夹被误识别为BUILD文件的Bug

---

src/blade/lex_yacc_target.py

On Linux:
1.  foo.l/foo.y --> foo.l.c/foo.y.h/foo.y.c
2.  foo.ll/foo.yy --> foo.ll.cc/foo.yy.h/foo.yy.cc

lex_yacc_library suffix pattern

---

src/blade/test_scheduler.py

- Tests don't stop by Ctrl+C:
- Tests stop by Ctrl+C immediately with this fix:

Terminate worker threads with Ctrl+C

---

src/blade/blade.py
src/blade/cc_targets.py
src/blade/java_targets.py
src/blade/proto_library_target.py
src/blade/rules_generator.py

- Generate env.Clean only if 'blade clean'
- Omits objs var when there is only one source in CcTarget

Optimize generated Sconstruct

---

src/blade/scons_helper.py

The patch fix the following critical issue:
Blade(info): ccache found
Blade(info): loading BUILDs...
Blade(info): loading done.
Blade(info): analyzing dependency graph...
Blade(info): analyzing done.
Blade(info): generating build rules...
Blade(info): CPP=cpp
Blade(info): CC=gcc
Blade(info): CXX=g++
Blade(info): LD=g++
Blade(info): generating done.
Blade(info): tunes the parallel jobs number(-j N) to be 4
scons: Reading SConscript files ...
UnboundLocalError: local variable 'blade_error_log' referenced before assignment:
File "/home/kimi/nimitz/SConstruct", line 21:
scons_helper.set_blade_error_log("build64_release/blade_scons.log.error")
File "/home/kimi/typhoon-blade/src/blade/scons_helper.py", line 68:
if blade_error_log:
Blade(error): building failure
Blade(info): cost time is …

fix a blade_error_log issue

---

src/blade/blade_util.py
src/blade/fatjar.py
src/blade/java_targets.py
src/blade/proto_library_target.py
src/blade/rules_generator.py
src/blade/scala_targets.py
src/blade/target.py
src/blade/toolchain.py

1. Change variable naming in JavaMixIn dependency handling methods(compile/package/test_deps) in order to unify scons and ninja build system.
- dep_jar_vars --> dep_jars: represent jars built by blade targets, including java_library(prebuilt)/scala_library/proto_library
- dep_jars --> maven_jars: represent jars introduced from maven_jar
2. Ninja build/rules for java_library/java_fat_library/java_binary/java_test
3. Ninja java build for proto_library
4. Ninja build/rules for scala_library/scala_fat_library/scala_test

Ninja build system part 2

---

src/blade/blade.py
src/blade/blade_main.py
src/blade/cc_targets.py
src/blade/command_args.py
src/blade/console.py
src/blade/java_targets.py
src/blade/scons_helper.py
src/blade/target.py

add --dry-run, --profiling
ninja support -j -k
merge --ninja-build and --scons-build into one single --native-builder
improve --generate-scons-only to --stop-after
enum args such as --color uses 'choices' instead of manual checking
support performance profiling

refactoring command args and add profiling

---

src/blade/target.py

Normally a target may have more than one output built by different rules, such as proto_library may generate various outputs according to the build targets and options. 
The output for each kind of the rule is usually a single path within build directory, but could be a list of path. Currently proto_library outputs for golang is recorded this way:
'gopkg'  ->  ['protobuf_go_path/common/framework/rpc/rpc_options.pb.go',
protobuf_go_path/common/framework/rpc/rpc_error_code.pb.go,
protobuf_go_path/common/framework/rpc/rpc_monitor.pb.go]

Fix Target._get_target_files when value is a list of paths

---

src/blade/fatjar.py

1. META-INF/blade/JAR.LIST for all the member jars aggregated
2. META-INF/blade/merge-info for conflicting entries of jars:
Path: targeting_id_allocation.xml
From: build64_release/app/qzap/service/targeting/parser.jar
Ignored: build64_release/app/qzap/service/targeting/analyzer.jar

Metadata for farjar

---

.travis.yml
src/blade/blade_util.py
src/blade/build_manager.py
src/blade/config.py
src/blade/rules_generator.py

Building with distcc/icecream may specify a large -jN depending on the build cluster setup to speed up compilation, N might be 2 or 3 times of local cpu cores. In this case out of memory is likely to occur due to ~N link jobs launched simultaneous.

Support max link jobs in config

---

src/blade/cc_targets.py

Cc library can should depends on `.h` files, but not `.a` files.
This change improves the build parallelism.

Optimize cc_library's dependence on pb library and etc

---

src/blade/build_manager.py

Split build.ninja into multiple small ninja files, using `include` to join them together.
This change is to prepare optimizing per-target ninja file generation.

split ninja files

---

install

Syntax
~ Expand to the variable $HOME or home directory of the current user
Example
profile=~/.bash_profile
profile="$HOME/.bash_profile"

Fixed dirName with ~ in shell

---

.github/workflows/python-package.yml
src/blade/pathlib.py

Update pathlib.py to fit python 3.10

---

src/blade/backend.py
src/blade/command_line.py

Add two profile-guided optimization realated command line arguments, '--profile-generate' and '--profile-use'. 
Please refer to the reference https://gcc.gnu.org/onlinedocs/gcc-10.1.0/gcc/Instrumentation-Options.html for details.

Add profile-guided optimization support

---

.codebeatignore
.gitignore
src/blade/cc_targets.py
src/blade/java_targets.py
src/blade/version.py
src/test/run.sh

- distutils is deprecated and was removed since python 3.12
- packanging is not a stdlib

Fix version library conflict

---

doc/en/build_rules/idl.md
doc/zh_CN/build_rules/idl.md
src/blade/proto_library_target.py

- Generate customed cpp filenames in proto_library.
- Pass customed options to plugins in proto_library

Support customed cpp_outs and options for plugins in proto_library

---

doc/en/config.md
doc/zh_CN/config.md
src/blade/config.py
src/blade/proto_library_target.py
vim/syntax/blade_config.vim

Codegen plugins might generate some unsafe code in pb.cc. In some test scenarios, the warning option needs to be enabled.

support enable warning when compiling pb.cc

---

src/blade/backend.py
src/test/blade_test.py
src/test/cc_binary_test.py
src/test/cc_plugin_test.py
src/test/cc_test_test.py
src/test/test_target_test.py

Based on [fix: exceed maximal length of bash when linking #927](https://github.com/chen3feng/blade-build/pull/927), put the target_linkflags parameters into rspfile
If the target depends on too many proto_library or use too many link_all_symbols on purpose, the --whole-archive may be too long to break the max length of bash single argument.
Ninja will start any command with /bin/sh -c "{command}". The command will act as a single argument in bash.
Query single argument max length: ```printf %d $((32 * $(getconf PAGE_SIZE) ))```

cc link puts target_linkflags into rspfile to resolve --whole-archive input exceed maximal length of bash

---

src/blade/gen_rule_target.py
src/blade/proto_library_target.py

Proto_library can depends on gen_rule. By this rule, we want to add some config deps in proto_library by gen_rule. However,  when the gen_rule is built incrementally, the proto is not trigger to recompile.
By looking at the generated ninja file, the outs of gen_rule are not configured in the dependencies of the proto compilation command. 
Here I add gen_rule's outputs to proto's directory depdency to resolve this problem.

add gen_rule outputs into proto_library dependency
